name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y file

      - name: Test JPG files
        run: |
          # Initialiser une variable pour suivre les erreurs
          ERROR=false
          
          # Vérifier tous les fichiers .jpg
          for f in $(find . -name "*.jpg"); do
            echo "Testing $f"
            # Vérifier si le fichier est une image JPEG
            if file "$f" | grep -q 'JPEG image data'; then
              echo "$f is a valid JPEG image."
            else
              echo "Error: $f is not a valid JPEG image."
              ERROR=true
            fi
          done

          # Si des fichiers non JPEG ont été trouvés, échouer le job
          if [ "$ERROR" = true ]; then
            echo "One or more files are not valid JPEG images."
            exit 1
          fi

  build-memory:
    needs: test-memory
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/memory .

  push-memory:
    needs: build-memory
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: docker push ${{secrets.DOCKER_USERNAME}}/memory
