name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y file

      - name: Test JPG files
        run: |
          for f in $(find . -name "*.jpg"); do
            echo "Testing $f"
            file $f
          done

  build-memory:
    needs: test-memory
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/memory .

  push-memory:
    needs: build-memory
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: docker login -u "${{secrets.DOCKER_USERNAME}}" --password "${{secrets.DOCKER_PASSWORD}}"

      - name: Push Docker image to DockerHub
        run: docker push ${{secrets.DOCKER_USERNAME}}/memory
