name: CI Pipeline

on: 
  push:
    branches:
      - develop

jobs:
  test-memory:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y file

      - name: Test JPG files
        run: | 
          for f in $(find . -name "*.jpg ); do
            echo "Testing $f"
            file $f
          done
